import "../styles/globals.css";

import Sidebar from "../components/NavBar/slidebar";
// import Footer from "../components/Footer";
// import NewsBanner from "../components/Banner/Banner";
import Providers from "../providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <NewsBanner /> */}

          <Sidebar />
          <main className="mt-20">{children}</main>
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
